# include ~/.config/HyprV/kitty/mocha.conf
# include ~/.config/kitty/nord.conf
# include ~/.config/kitty/kitty-themes/themes/Nova.conf
# include ~/.config/ricemood/ricemood-theme.conf
# font_family      jetbrains mono nerd font
# font_family      lekton mono nerd font

# Allow dynamic color changes
include ~/.config/kitty/current.conf
allow_remote_control yes

# Font
font_family      JetBrains Mono Nerd Font
font_size 10
bold_font        auto
italic_font      auto
bold_italic_font auto

mouse_hide_wait  2.0

shell fish

url_color        #0087bd
url_style        dotted

#Close the terminal without confirmation
confirm_os_window_close 0

# background_opacity 0.95
term xterm-kitty

extended-keys    always

clipboard_control write-clipboard write-primary write-clipboard-on-select

cursor_shape     block
cursor_trail 1

map ctrl+plus  change_font_size all +1
map ctrl+equal  change_font_size all +1
map ctrl+kp_add  change_font_size all +1
map ctrl+minus       change_font_size all -1
map ctrl+underscore       change_font_size all -1
map ctrl+kp_subtract       change_font_size all -1
