[[manager.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on   = "i"
run  = "plugin max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[manager.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

[[manager.prepend_keymap]]
on   = "<C-j>"
run  = "arrow 1"
desc = "Smart filter"

[[manager.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

[[manager.prepend_keymap]]
on = [ ";", "w" ]
run = "cd ~"
desc = "Home directory"

[[manager.prepend_keymap]]
on = [ ";", "d" ]
run = "cd ~/Downloads"
desc = "Downloads"

[[manager.prepend_keymap]]
on = [ ";", "c" ]
run = "cd ~/.config/"
desc = "Original launch dir"

[[manager.prepend_keymap]]
on = [ ";", "j" ]
run = "cd ~/projets/"
desc = "projets"
