[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "i"
run  = "plugin max-preview"
desc = "Maximize or restore preview"

[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on   = "<C-j>"
run  = "arrow 1"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on = [ ";", "w" ]
run = "cd ~"
desc = "Home directory"

[[mgr.prepend_keymap]]
on = [ ";", "d" ]
run = "cd ~/Downloads"
desc = "Downloads"

[[mgr.prepend_keymap]]
on = [ ";", "c" ]
run = "cd ~/.config/"
desc = "Original launch dir"

[[mgr.prepend_keymap]]
on = [ ";", "j" ]
run = "cd ~/projets/"
desc = "projets"

[[mgr.prepend_keymap]]
on = [ ";", "u" ]
run = "cd /run/media/ewan/"
desc = "projets"

[[mgr.prepend_keymap]]
on = "y"
run = [ 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]

[[mgr.prepend_keymap]]
on = [ "S" ]
run = '''shell 'fish -c "share \"$@\""' --confirm'''
desc = "Share file"

[[mgr.prepend_keymap]]
on = [ "s" ]
run = "plugin fzf"
desc = "Fuzzy search in current file"
