$primary_paletteKeyColor = 2d8477
$secondary_paletteKeyColor = 627c76
$tertiary_paletteKeyColor = 5d7a93
$neutral_paletteKeyColor = 717876
$neutral_variant_paletteKeyColor = 6f7976
$background = 0e1513
$onBackground = dde4e1
$surface = 0e1513
$surfaceDim = 0e1513
$surfaceBright = 343b39
$surfaceContainerLowest = 090f0e
$surfaceContainerLow = 171d1b
$surfaceContainer = 1a211f
$surfaceContainerHigh = 252b2a
$surfaceContainerHighest = 303634
$onSurface = dde4e1
$surfaceVariant = 3f4946
$onSurfaceVariant = bec9c5
$inverseSurface = dde4e1
$inverseOnSurface = 2b3230
$outline = 899390
$outlineVariant = 3f4946
$shadow = 000000
$scrim = 000000
$surfaceTint = 83d5c6
$primary = 83d5c6
$onPrimary = 003731
$primaryContainer = 005047
$onPrimaryContainer = 9ff2e2
$inversePrimary = 006b5f
$secondary = b1ccc6
$onSecondary = 1c3530
$secondaryContainer = 354e49
$onSecondaryContainer = cde8e1
$tertiary = accae5
$onTertiary = 143349
$tertiaryContainer = 7794ad
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = 9ff2e2
$primaryFixedDim = 83d5c6
$onPrimaryFixed = 00201c
$onPrimaryFixedVariant = 005047
$secondaryFixed = cde8e1
$secondaryFixedDim = b1ccc6
$onSecondaryFixed = 06201c
$onSecondaryFixedVariant = 334b47
$tertiaryFixed = cbe6ff
$tertiaryFixedDim = accae5
$onTertiaryFixed = 001e30
$onTertiaryFixedVariant = 2c4a60
$term0 = 343434
$term1 = 769e00
$term2 = 63e2b3
$term3 = 8cfcc1
$term4 = 76b6ad
$term5 = 7aaee9
$term6 = 87d9c1
$term7 = cedcd1
$term8 = 9ba59c
$term9 = 85b900
$term10 = 57f7c1
$term11 = d0ffe2
$term12 = a4c8bf
$term13 = a2c0f7
$term14 = 90edd0
$term15 = ffffff
$rosewater = f1f3e5
$flamingo = e3e4c5
$pink = bae2ff
$mauve = 5bd0e0
$red = 8ab5ff
$maroon = c6c177
$peach = a9daac
$yellow = d5fae3
$green = 92f2d6
$teal = a0eedf
$sky = 94eae1
$sapphire = 71d8d2
$blue = 56ced1
$lavender = 84dae0
$klink = 009796
$klinkSelection = 009796
$kvisited = 008ca9
$kvisitedSelection = 008ca9
$knegative = 838f00
$knegativeSelection = 838f00
$kneutral = 34c359
$kneutralSelection = 34c359
$kpositive = 00bfa0
$kpositiveSelection = 00bfa1
$text = dde4e1
$subtext1 = bec9c5
$subtext0 = 899390
$overlay2 = 77807d
$overlay1 = 646d6a
$overlay0 = 535b59
$surface2 = 424a48
$surface1 = 313937
$surface0 = 202725
$base = 0e1513
$mantle = 0e1513
$crust = 0d1412
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
