# Load an image into memory
preload = /home/ewan/.config/wallpaper/demon_slayer.png

# Apply it to a specific monitor
# wallpaper = monitor, /home/me/amongus.png

# Or apply to all monitors without a set wallpaper
# wallpaper = , /home/ewan/.config/wallpaper/demon_slayer.png
wallpaper = , /home/ewan/.config/wallpaper/lune_verte.jpg
