# Layout Configuration
# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/
# See https://wiki.hyprland.org/Configuring/Master-Layout/

dwindle {
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
    force_split = 2
}

master {
    new_status = master
}
