# Monitor Configuration
# See https://wiki.hyprland.org/Configuring/Monitors/

#monitor=,highres,120,2
monitor=eDP-1,highrr,0x0,2,vrr,1
# monitor=eDP-1,3072x1920@119.93,0x0,2
# monitor = , preferred,0x-1080, 1
monitor=,3072x1920,auto,1,mirror,eDP-1
# monitor = , preferred, auto, 1, mirror
# monitor=,1600x900,auto,1,mirror

# Dual monitor example on G15 Strix
# eDP-1 is the built in monitor while DP-1 is external
# Both monitors here are at 1440 and 165Hz
# DP-1 is on the left and  eDP-1 is on the right
# monitor=eDP-1,2560x1440@165,2560x0,1
