# Window Rules
# See https://wiki.hyprland.org/Configuring/Window-Rules/

# Example windowrule v1
#windowrule = float, ^(kitty)$
# windowrule = float,^(pavucontrol)$
# windowrule = float,^(blueman-manager)$
# windowrule = float,^(nm-connection-editor)$
# windowrule = workspace 2 silent,^(firefox)$
# windowrule = workspace 3 silent,^(chromium)$
# windowrule = workspace 9 silent,^(discord)$
# windowrule = workspace 9 silent,^(vesktop)$

windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = float, class:io.github.Qalculate.qalculate-qt
windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = float, class:^(nm-connection-editor)$
windowrulev2 = workspace 2 silent, class:^(firefox)$
windowrulev2 = workspace 1 silent, class:^(chromium)$
windowrulev2 = workspace 5 silent, class:(Notion)
windowrulev2 = workspace 9 silent, class:^(discord)$
windowrulev2 = workspace 9 silent, class:^(vesktop)$
windowrulev2 = workspace 9 silent, class:^(equibop)$

windowrulev2 = float, class:(floatingTerm)
windowrulev2 = size 1000 700,class:(floatingTerm)
windowrulev2 = center, class:(floatingTerm)

windowrulev2 = float,title:^(Floating Window - Show Me The Key)$
windowrulev2 = noinitialfocus,title:^(Floating Window - Show Me The Key)$
windowrulev2 = noborder,title:^(Floating Window - Show Me The Key)$
windowrulev2 = move 1033 842,title:^(Floating Window - Show Me The Key)$
windowrulev2 = size 491 50,title:^(Floating Window - Show Me The Key)$
windowrulev2 = center, class:(floatingTerm)
windowrulev2 = pin,title:^(Floating Window - Show Me The Key)$

# Opacity rules
windowrulev2 = opacity 1 1,class:^(kitty)$
# windowrulev2 = animation popin,class:^(kitty)$,title:^(update-sys)$
# windowrulev2 = opacity 0.8 0.8,class:^(kitty)$,title:^(ranger)$
windowrulev2 = animation popin,class:^(chromium)$
windowrulev2 = move cursor -3% -105%,class:^(rofi)$
windowrulev2 = noanim,class:^(rofi)$
windowrulev2 = opacity 0.8 0.6,class:^(rofi)$
# windowrulev2 = opacity 0.8 0.8, fullscreen:1
