# Font
[main]
font=JetBrains Mono Nerd Font:size=9
shell=fish

# Cursor
[cursor]
style=block
blink=no

# Colors - matching kitty theme
[colors]
background=1E222A
foreground=f8f8f2

## Cursor colors
cursor=bbbbbb bbbbbb

## Selection
selection-foreground=1e1f28
selection-background=44475a

## Normal colors
regular0=000000  # black
regular1=769E00  # red
regular2=63E2B3  # green
regular3=8CFCC1  # yellow
regular4=76B6AD  # blue
regular5=7AAEE9  # magenta
regular6=87D9C1  # cyan
regular7=bbbbbb  # white

## Bright colors
bright0=545454   # bright black
bright1=769E00   # bright red
bright2=63E2B3   # bright green
bright3=8CFCC1   # bright yellow
bright4=76B6AD   # bright blue
bright5=7AAEE9   # bright magenta
bright6=87D9C1   # bright cyan
bright7=ffffff   # bright white

## URL color
urls=0087bd
